-- AlterTable
ALTER TABLE "Blog" ALTER COLUMN "category" SET DEFAULT '',
ALTER COLUMN "like" SET DEFAULT 0,
ALTER COLUMN "posted_on" DROP NOT NULL,
ALTER COLUMN "posted_on" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "tags" SET DEFAULT '';
